# ============================================================
#  SisIncidentes — Configuração de Desenvolvimento
# ============================================================

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.seguranca.sisincidentes=DEBUG

# JWT Security
# Em ambiente de DEV, usamos uma chave fixa para facilitar os testes locais.
# A chave deve ter pelo menos 256 bits (32 caracteres) para o algoritmo HS256.
api.security.token.secret=4f61746820536973496e636964656e74657320536563726574204b65792032303234
api.security.token.expiration-ms=86400000

# JPA - Mostra SQL no console
spring.jpa.show-sql=true
